services:
  - type: web
    name: house-price-prediction
    runtime: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --timeout=120 --bind 0.0.0.0:$PORT
